### ISSUE TITLE
Uncaught exception: cannot load such file -- libxml_ruby even if it's installed. 

### ISSUE THREAD

**Issue by SP8890** [gorn/rspreadsheet#62]
The libxml seems installed but still thowing this error. below are some configs. please advise. Thanks 

Gem Environment :
RubyGems Environment:
RUBYGEMS VERSION: 2.7.6
RUBY VERSION: 2.5.3 (2018-10-18 patchlevel 105) [x64-mingw32]
INSTALLATION DIRECTORY: C:/Ruby25-x64/lib/ruby/gems/2.5.0
USER INSTALLATION DIRECTORY: C:/Users/Sachin/.gem/ruby/2.5.0
RUBY EXECUTABLE: C:/Ruby25-x64/bin/ruby.exe
EXECUTABLE DIRECTORY: C:/Ruby25-x64/bin
SPEC CACHE DIRECTORY: C:/Users/Sachin/.gem/specs
SYSTEM CONFIGURATION DIRECTORY: C:/ProgramData
RUBYGEMS PLATFORMS:
ruby
x64-mingw32
GEM PATHS:
C:/Ruby25-x64/lib/ruby/gems/2.5.0
C:/Users/Sachin/.gem/ruby/2.5.0
GEM CONFIGURATION:
:update_sources => true
:verbose => true
:backtrace => false
:bulk_threshold => 1000
REMOTE SOURCES:
https://rubygems.org/
SHELL PATH:
C:\Program Files (x86)\Common Files\Oracle\Java\javapath
C:\Program Files\Common Files\Oracle\Java\javapath
C:\Windows\System32
C:\Windows
C:\Windows\System32\wbem
C:\Windows\System32\WindowsPowerShell\v1.0\
C:\Windows\System32\OpenSSH\
C:\Program Files\SourceGear\Common\DiffMerge\
C:\Program Files\Java\jdk-16.0.1\bin
C:\Program Files\apache-maven-3.8.1\bin
C:\Program Files (x86)\GnuPG\bin
C:\Program Files\Git\cmd
C:\Program Files\nodejs\
C:\soft
C:\Ruby25-x64\bin
C:\Program Files\Java\jdk-16.0.1\bin
C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1.2\bin
C:\Program Files\JetBrains\WebStorm 2021.1.2\bin
C:\Users\Sachin\AppData\Local\Programs\Microsoft VS Code\bin
C:\Program Files\nodejs\
C:\Users\Sachin\AppData\Roaming\npm
C:\Program Files\JetBrains\RubyMine 2021.2.3\bin
C:\Users\Sachin\AppData\Local\Microsoft\WindowsApps
bundle show libxml-ruby

C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/libxml-ruby-2.9.0-x64-mingw32

**Comment by kalidor** [comment]
This is not an error. This is all the environment variables printed, nothing more.

**Comment by SP8890** [comment]
Hi @kalidor, thanks for notifying,  please find attached, 

**Code**  : 
require 'rspreadsheet'

book = Rspreadsheet.open('/home/rahul/Downloads/spreadsheet_test.ods')

sheet = book.worksheets(1)

sheet.B2 = "578"

book.save

**Error**  : 

C:\Ruby25-x64\bin\bundle.bat exec C:\Ruby25-x64\bin\ruby.exe C:\Users\Sachin\.gem\ruby\2.5.0\gems\ruby-debug-ide-2.3.1\bin\rdebug-ide --key-value --step-over-in-blocks --disable-int-handler --evaluation-timeout 10 --evaluation-control --time-limit 100 --memory-limit 0 --rubymine-protocol-extensions --port 50233 --host 0.0.0.0 --dispatcher-port 50234 -- C:/Users/Sachin/RubymineProjects/selenium_ruby/spreadsheet_example/r_spreadsheet_test.rb
Your RubyGems version (2.7.6)) has a bug that prevents `required_ruby_version` from working for Bundler. Any scripts that use `gem install bundler` will break as soon as Bundler drops support for your Ruby version. Please upgrade RubyGems to avoid future breakage and silence this warning by running `gem update --system 3.2.3`
Fast Debugger (ruby-debug-ide 2.3.1, debase 2.3.2, file filtering is supported, block breakpoints supported, smart steps supported, obtaining return values supported, partial obtaining of instance variables supported) listens on 0.0.0.0:50233
Uncaught exception: cannot load such file -- libxml
        C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspreadsheet-0.5.3/lib/rspreadsheet/workbook.rb:2:in `require'
        C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspreadsheet-0.5.3/lib/rspreadsheet/workbook.rb:2:in `<top (required)>'
        C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspreadsheet-0.5.3/lib/rspreadsheet.rb:2:in `require'
        C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspreadsheet-0.5.3/lib/rspreadsheet.rb:2:in `<top (required)>'
        C:/Users/Sachin/RubymineProjects/selenium_ruby/spreadsheet_example/r_spreadsheet_test.rb:1:in `require'
        C:/Users/Sachin/RubymineProjects/selenium_ruby/spreadsheet_example/r_spreadsheet_test.rb:1:in `<top (required)>'

Process finished with exit code 1

**Gem File**: 
ruby '2.5.3'
source 'https://rubygems.org'

gem 'selenium-webdriver'
gem 'ffi'
gem 'spreadsheet'
gem 'roo'
gem 'nokogiri'
gem 'yalab-ruby-ods', '~> 0.0.0'
gem 'yomu', '~> 0.2.4'
gem 'jekyll-curse'
gem 'win32-file', '~> 0.8.2'
gem 'rspreadsheet', '~> 0.5.3'
