### ISSUE TITLE
Charts in source .ods file cause an error when trying to save.

### ISSUE THREAD

**Issue by AidanofVT** [gorn/rspreadsheet#65]
I have a simple spreadsheet with a simple chart. I'm trying to copy the .ods file, add some data, and save. This yields the following error:
```
/home/aidan/.local/share/gem/ruby/3.0.0/gems/rspreadsheet-0.5.3/lib/rspreadsheet/workbook.rb:140:in `block (2 levels) in update_manifest_xml': This should not happen (RuntimeError)
        from /home/aidan/.local/share/gem/ruby/3.0.0/gems/rspreadsheet-0.5.3/lib/rspreadsheet/workbook.rb:131:in `each'
        from /home/aidan/.local/share/gem/ruby/3.0.0/gems/rspreadsheet-0.5.3/lib/rspreadsheet/workbook.rb:131:in `block in update_manifest_xml'
        from /home/aidan/.local/share/gem/ruby/3.0.0/gems/rspreadsheet-0.5.3/lib/rspreadsheet/workbook.rb:130:in `each'
        from /home/aidan/.local/share/gem/ruby/3.0.0/gems/rspreadsheet-0.5.3/lib/rspreadsheet/workbook.rb:130:in `update_manifest_xml'
        from /home/aidan/.local/share/gem/ruby/3.0.0/gems/rspreadsheet-0.5.3/lib/rspreadsheet/workbook.rb:117:in `update_zip_manifest_and_content_xml'
        from /home/aidan/.local/share/gem/ruby/3.0.0/gems/rspreadsheet-0.5.3/lib/rspreadsheet/workbook.rb:76:in `block in save'
        from /home/aidan/.local/share/gem/ruby/3.0.0/gems/rspreadsheet-0.5.3/lib/rspreadsheet/tools.rb:200:in `block in output_to_zip_stream'
        from /home/aidan/.local/share/gem/ruby/3.0.0/gems/rubyzip-2.3.2/lib/zip/file.rb:125:in `open'
        from /home/aidan/.local/share/gem/ruby/3.0.0/gems/rspreadsheet-0.5.3/lib/rspreadsheet/tools.rb:199:in `output_to_zip_stream'
        from /home/aidan/.local/share/gem/ruby/3.0.0/gems/rspreadsheet-0.5.3/lib/rspreadsheet/workbook.rb:75:in `save'
        from /home/aidan/.local/share/gem/ruby/3.0.0/gems/rspreadsheet-0.5.3/lib/rspreadsheet/workbook.rb:82:in `save'
```
In my limited testing, it seems that having any chart at all in the file causes an error. I understand that this gem isn't actively maintained, but some help with this would be appreciated.

-Aidan

**Comment by AidanofVT** [comment]
GPT4 fixes the issue in my case by changing line 135 of workbook.rb to remove the preceding "./" from image.internal_filename when it gets assigned to @ifname. I do not have the expertise to suggest whether this is advisable as a general fix, but perhaps it offers a clue as to an improvement to this gem.
